#!/bin/sh

set -eo pipefail

readonly message="${1:-quicksave}"

echo "Commiting recent changes with message: '$message'"
git add -A > /dev/null 2>&1
git commit --no-verify -m "$message" > /dev/null 2>&1