#!/bin/sh

set -eo pipefail

readonly message="${1:-goal}"

echo "Setting up goal for: '$message'"

git commit --allow-empty --no-verify -m "$message" > /dev/null 2>&1

echo "Run 'git save' to save your changes, and 'git back' to revert. When you're done with your work, run 'git done'."